In [1]:
import jax 
import jax.numpy as jnp
from jax import lax

In [8]:
x=jnp.ones((2,10,3))

In [9]:
x

Array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [10]:
kernel=jnp.array([[[1.0],[2.0],[1.0]]])
kernel

Array([[[1.],
        [2.],
        [1.]]], dtype=float32)

In [24]:
def conv_layer(x,kernel):
    dn=lax.conv_dimension_numbers(x.shape,kernel.shape,('NHC','HIO','NHC'))
    output=lax.conv_general_dilated(x,kernel,(1,),'VALID',dimension_numbers=dn)
    return output

In [25]:
print(conv_layer(x,kernel).shape)

(1, 22, 1)


In [20]:
temp_data = jnp.array([60, 61, 62, 62, 63, 63, 64, 65, 66, 67, 68, 70, 85, 86, 87, 85, 80, 78, 75, 72, 70, 68, 67, 65])
x=temp_data.reshape((1,24,1))
x=x.astype(jnp.float32)
kernel=jnp.array([[[-1.0]],[[0.0]],[[1.0]]])
kernel=kernel.astype(jnp.float32)

In [26]:
conv_layer(x,kernel).flatten()

Array([ 2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  3., 17., 16.,  2.,
       -1., -7., -7., -5., -6., -5., -4., -3., -3.], dtype=float32)